### ISSUE TITLE
1번 오익수 (random함수 import 및 세팅)

### ISSUE THREAD

**Issue by iam52** [MontyHall-Simulation/montyhall-simulation#1]
## 설명(Description)

Random 모듈을 import하여 리스트 a, b, c를 door 변수에 할당하고,
문을 바꾸지 않은 경우의 수와 문을 바꾼 경우의 수를 0으로 초기하고,
횟수를 100000회로 설정합니다.

## 할 일(Tasks)

- [ ] Random 모듈 import
- [ ] door 변수에 a, b, c로 이루어진 리스트 생성
- [ ] 문을 바꾸지 않은 경우의 수 초기화
- [ ] 문을 바꾼 경우의 수 초기화

## 참조(Referencs)

- [montyhall](https://enjoyso.tistory.com/87)

**Comment by iam52** [comment]
조장님 저는 두 파트로 나눠봤습니다. 검토해주시면 밑에 나머지 부분 올리겠습니다.

**Comment by seakjh** [comment]
> 조장님 저는 두 파트로 나눠봤습니다. 검토해주시면 밑에 나머지 부분 올리겠습니다.

어떤 라이브러리를 import하는지랑
어떤 이름의 변수를썼는지 등을 명시하면 좋을거같아요

**Comment by iam52** [comment]
다른데서 시작해버렸네요.
말씀하신 내용 수정했습니다.
